/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopInvitationsRouteImport } from './routes/workshop-invitations'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PmRouteImport } from './routes/pm'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CapacityBuildingRouteImport } from './routes/capacity-building'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as CapacityBuildingIdRouteImport } from './routes/capacity-building.$id'

const WorkshopInvitationsRoute = WorkshopInvitationsRouteImport.update({
  id: '/workshop-invitations',
  path: '/workshop-invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PmRoute = PmRouteImport.update({
  id: '/pm',
  path: '/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityBuildingRoute = CapacityBuildingRouteImport.update({
  id: '/capacity-building',
  path: '/capacity-building',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const CapacityBuildingIdRoute = CapacityBuildingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CapacityBuildingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/capacity-building': typeof CapacityBuildingRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/manager': typeof ManagerRoute
  '/pm': typeof PmRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/select': typeof SelectRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workshop-invitations': typeof WorkshopInvitationsRoute
  '/capacity-building/$id': typeof CapacityBuildingIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/capacity-building': typeof CapacityBuildingRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/manager': typeof ManagerRoute
  '/pm': typeof PmRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/select': typeof SelectRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workshop-invitations': typeof WorkshopInvitationsRoute
  '/capacity-building/$id': typeof CapacityBuildingIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/capacity-building': typeof CapacityBuildingRouteWithChildren
  '/companies': typeof CompaniesRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/manager': typeof ManagerRoute
  '/pm': typeof PmRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/select': typeof SelectRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/workshop-invitations': typeof WorkshopInvitationsRoute
  '/capacity-building/$id': typeof CapacityBuildingIdRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/capacity-building'
    | '/companies'
    | '/documents'
    | '/manager'
    | '/pm'
    | '/projects'
    | '/reports'
    | '/select'
    | '/settings'
    | '/users'
    | '/workshop-invitations'
    | '/capacity-building/$id'
    | '/companies/$id'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/capacity-building'
    | '/companies'
    | '/documents'
    | '/manager'
    | '/pm'
    | '/projects'
    | '/reports'
    | '/select'
    | '/settings'
    | '/users'
    | '/workshop-invitations'
    | '/capacity-building/$id'
    | '/companies/$id'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/capacity-building'
    | '/companies'
    | '/documents'
    | '/manager'
    | '/pm'
    | '/projects'
    | '/reports'
    | '/select'
    | '/settings'
    | '/users'
    | '/workshop-invitations'
    | '/capacity-building/$id'
    | '/companies/$id'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  CapacityBuildingRoute: typeof CapacityBuildingRouteWithChildren
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ManagerRoute: typeof ManagerRoute
  PmRoute: typeof PmRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SelectRoute: typeof SelectRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  WorkshopInvitationsRoute: typeof WorkshopInvitationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop-invitations': {
      id: '/workshop-invitations'
      path: '/workshop-invitations'
      fullPath: '/workshop-invitations'
      preLoaderRoute: typeof WorkshopInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm': {
      id: '/pm'
      path: '/pm'
      fullPath: '/pm'
      preLoaderRoute: typeof PmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building': {
      id: '/capacity-building'
      path: '/capacity-building'
      fullPath: '/capacity-building'
      preLoaderRoute: typeof CapacityBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/capacity-building/$id': {
      id: '/capacity-building/$id'
      path: '/$id'
      fullPath: '/capacity-building/$id'
      preLoaderRoute: typeof CapacityBuildingIdRouteImport
      parentRoute: typeof CapacityBuildingRoute
    }
  }
}

interface CapacityBuildingRouteChildren {
  CapacityBuildingIdRoute: typeof CapacityBuildingIdRoute
}

const CapacityBuildingRouteChildren: CapacityBuildingRouteChildren = {
  CapacityBuildingIdRoute: CapacityBuildingIdRoute,
}

const CapacityBuildingRouteWithChildren =
  CapacityBuildingRoute._addFileChildren(CapacityBuildingRouteChildren)

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  CapacityBuildingRoute: CapacityBuildingRouteWithChildren,
  CompaniesRoute: CompaniesRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ManagerRoute: ManagerRoute,
  PmRoute: PmRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SelectRoute: SelectRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  WorkshopInvitationsRoute: WorkshopInvitationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
